### ISSUE TITLE
Add pH option for major microspecies in speciation batch mode

### ISSUE THREAD

**Issue by popenc** [quanted/cts_app#103]

**Comment by popenc** [comment]
@koopmans-michaela @cstevens227 When walking through the CTS request procedure for speciation in batch mode, it appears that the major microspecies request is already sending the user-entered pH.

Is that something y'all could verify?

**Comment by koopmans-michaela** [comment]
I started testing this and it tentatively looks like it's working. My computer did an update and once I got back to test more, CTS was down again. I'll finish testing this later, but it's looking promising at least.

Minor side note: For the "output is ready, download at top right of page" message, can we maybe take out the "right" part since it looks like it isn't necessarily on the right side always?

**Comment by popenc** [comment]
Thanks for looking into that. I know Tom's doing some work on server 1 right now getting everything back to normal, which is probably why the site is up and down, and up and down.

I'll add the output ready moved as an issue so I don't forget about it.

**Comment by koopmans-michaela** [comment]
Done verifying. Looks good.
